### ISSUE TITLE
postprocess.ts failing

### ISSUE THREAD

**Issue by badgley** [pierrotsmnrd/flat_data_py_example#1]
I've been playing around with this example -- I've been able to adapt your workflow and make a few of my own flat data repos that have been working really well.

Sometime yesterday, my GitHub Action/post-processing workflows started to fail. It looks like this example has also started to fail as well. Here's the output I'm getting:

```ts
 Warning Implicitly using latest version (1.0.0) for https://deno.land/x/url_join/mod.ts
17
  error: Relative import path "ssf" not prefixed with / or ./ or ../ from "https://cdn.deno.land/sheetjs/versions/v0.16.8/raw/types/index.d.ts"
18
  Error: Error: Command failed: deno run -q -A --unstable ./postprocess.ts active-conus-fires.csv
19
  Warning Implicitly using latest version (1.0.0) for https://deno.land/x/url_join/mod.ts
20
  error: Relative import path "ssf" not prefixed with / or ./ or ../ from "https://cdn.deno.land/sheetjs/versions/v0.16.8/raw/types/index.d.ts"
```

It looks like you're running into the same problem: https://github.com/pierrotsmnrd/flat_data_py_example/actions/runs/920123080.

Any thoughts on how to resolve?

Thanks so much for making this example and please let me know if I can help at all in tracking down this issue.

**Comment by pierrotsmnrd** [comment]
Hi @badgley  ! thanks for reaching out :) 

I made this example because I am mainly a python programmer. I have no clue what Deno does here, it's out of my skills. 
I thought for a moment it was related to the CDN issues that occured worldwide so waited, expecting it to settle down. Unfortunately, it doesn't. 

I tried to fix the same issue as it also appears on a project of mine  : https://github.com/pierrotsmnrd/earthquakes 
trying to change `flat.yml` to `githubocto/flat@v3` but didn't succeed. 

I'm clueless for the moment and don't have much time these days to dig deeper :/ any help will be greatly appreciated.

**Comment by badgley** [comment]
yup -- im in the same boat! know python, have mostly avoided JS/TS. I'll see if I can figure out the right question to ask the deno folks and will keep you posted if I hear anything.

**Comment by cczhu** [comment]
I think this error may have been due to an upstream issue with Deno described in githubocto/flat#45, which has just been fixed a few minutes ago.

**Comment by badgley** [comment]
alright so it looks like we can just remove the import of mod.ts and we're good to go! I opened a PR

**Comment by pierrotsmnrd** [comment]
Hi @badgley  :) thanks for your help. I can't see your PR though. If you don't mind, I'm going to replicate your commit and see if that works.

**Comment by pierrotsmnrd** [comment]
That worked ! :) thanks @badgley !
